### ISSUE TITLE
Compile a complete set of images in the correct format

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/digital-fauvel#1]
95 images total (11.psd through 105.psd inclusive).

### How to test

- [x] Wait for the Mirador instance to be set up, and an URL to be added here.
- [ ] Confirm that the list of images in #2 is visible in that mirador instance, and that it can be zoomed, panned, etc, as IIIF images can be in Mirador.
- [ ] Open Chrome Developer Tools (Command-Option-J in Chrome), choose Network tab, and open JS console below, and watch network traffic as you zoom, pan, etc, and confirm there are no JS errors, or Network errors as you do.

**Comment by jamiefolsom** [comment]
Anna mentioned that there would likely be two more images; 9 and 10. Those can be added when they're ready.

**Comment by jamiefolsom** [comment]
Also, all PSDs, Converted TIFFs and Pyramidal TIFFs will be stored in this repository, via LFS.

**Comment by SteveMarvin** [comment]
See comment on #3. I was able to do this once, and I was in fact able to see all 95 images and move through them. However, I am no longer able to do so, and the instance is no longer visible. Despite seeing this work correctly once, I am not going to ACCEPT this issue until it can be done again.

**Comment by jamiefolsom** [comment]
Hi @SteveMarvin -- forgot to update the issue when I moved the site. New location: http://fauvel.archivengine.com/

**Comment by SteveMarvin** [comment]
There seems to be a little confusion here. If I navigate directly to http://fauvel.archivengine.com/, there is already an instance of Fauvel added there, and a new one cannot be added via URL. If I go to the Mirador site, I can successfully add a Fauvel instance via URL there. 

Loading the http://fauvel.archivengine.com/ site generates the following error, but no other errors during use:

![screen shot 2017-09-05 at 3 50 14 pm](https://user-images.githubusercontent.com/18423533/30080541-f30b959e-9251-11e7-8e68-1c9c48378934.png)

Loading the Mirador site generates the following errors on load, but no further errors during use:
![screen shot 2017-09-05 at 3 51 17 pm](https://user-images.githubusercontent.com/18423533/30080605-26ec2efa-9252-11e7-87dd-543f5a865eb9.png)

These errors are the same as described here: https://github.com/performant-software/digital-fauvel/issues/3#issuecomment-327197188

**Comment by jamiefolsom** [comment]
@SteveMarvin 

The missing translation file is a good catch. Would you open a new issue for that, and I will address it. It's related to a feature which didn't exist independently of any other ticket.

This issue was to create the images themselves, and we were using mirador only to check that they were all there. #3 on the other hand *requires* mirador; that's the easiest way to confirm that the manifest is complete and functional. Separate thing from creation of the images.

Sorry for the confusion, and thanks!

**Comment by SteveMarvin** [comment]
Throttling network speed makes for a laborious experience, but generates no errors. ;-) 👍

**Comment by jamiefolsom** [comment]
Thanks for checking on slow network speed @SteveMarvin -- that's actually an issue that came up even for those of us on non-throttled network speeds. I will open an issue to track that.

**Comment by SteveMarvin** [comment]
It only got really bad when I reduced it to Slow 3G speeds. Anything faster was fairly usable.
