### ISSUE TITLE
Set up a host to run the IIP image server

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/digital-fauvel#2]
**Note: No PRs for this first set up setup issues**

### How to test

1. Go to http://iip.textlab.org/?IIIF=fauvel/8.tiff/full/1000,/0/default.jpg. You should see the first image in the volume.
2. Then for the following filenames, substituted into the URL, you should see the other 94 or so images. 

11.tiff
12.tiff
13.tiff
14.tiff
15.tiff
16.tiff
17.tiff
18.tiff
19.tiff
20.tiff
21.tiff
22.tiff
23.tiff
24.tiff
25.tiff
26.tiff
27.tiff
28.tiff
29.tiff
30.tiff
31.tiff
32.tiff
33.tiff
34.tiff
35.tiff
36.tiff
37.tiff
38.tiff
39.tiff
40.tiff
41.tiff
42.tiff
43.tiff
44.tiff
45.tiff
46.tiff
47.tiff
48.tiff
49.tiff
50.tiff
51.tiff
52.tiff
53.tiff
54.tiff
55.tiff
56.tiff
57.tiff
58.tiff
59.tiff
60.tiff
61.tiff
62.tiff
63.tiff
64.tiff
65.tiff
66.tiff
67.tiff
68.tiff
69.tiff
70.tiff
71.tiff
72.tiff
73.tiff
74.tiff
75.tiff
76.tiff
77.tiff
78.tiff
79.tiff
80.tiff
81.tiff
82.tiff
83.tiff
84.tiff
85.tiff
86.tiff
87.tiff
88.tiff
89.tiff
90.tiff
91.tiff
92.tiff
93.tiff
94.tiff
95.tiff
96.tiff
97.tiff
98.tiff
99.tiff
100.tiff
101.tiff
102.tiff
103.tiff
104.tiff
105.tiff

**Comment by SteveMarvin** [comment]
Never actually had 95 tabs open at once in a browser, so inadvertently tested that, too. ;-)

All files checked out nicely, there was an image served for every URL. 👍
