### ISSUE TITLE
Plan for how mirador will render annotations

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/digital-fauvel#27]
Options

* Annotations in mirador are displayed using the QTip jquery plugin
* Mirador now has several annotation strategies; SVG might be the right one for transcriptions.

Steps

- Storage: Manifest points to AnnotationList files
- AnnotationLists contain all annotations for a given folio page/canvas
- Annotations (per line): toggle between fragmentSelector and SVG selector
- SVG: get content from annotation resource, insert SVG <text> into <svg> after <path>, or <rect>
- When to update SVG: convert time, load time or render time?
- Render all annotations on load; with no qtip viewer

**Comment by akstuhl** [comment]
Proposed + tested approach: after annotation selector rectangles are added to the canvas, use Mirador's paper.js scope to retrieve their corresponding content strings and render these as PointText objects, using the rectangle bounds to set the position and sizing for the text. 

Still to be determined:
- Is there an existing event in Mirador / OpenSeaDragon that will work well as the trigger for the text rendering process?
- Does it make sense to run this listener script as a plugin?
- Should provide configuration options for font family, font color, padding within rect, font size; others?

Example script:
```
 var annotationTextPad = 20;
 mirador.eventEmitter.subscribe("parsedSVG", function(event, items, windowId) {
   if (items) {
     items.forEach(function(item) {
       if (item.data && item.data.annotation && item.data.annotation.resource) {
         var resource = item.data.annotation.resource;
         var bounds = item.bounds;
         if (resource.length > 0) resource = resource[0];
         if (resource.chars && bounds) {
           var t = new paper.PointText();
           t.point = new paper.Point(bounds.x + annotationTextPad, bounds.y + bounds.height - annotationTextPad);
           t.content = resource.chars;
           t.fontSize = (bounds.height - 2 * annotationTextPad) + "px";
         }
       }
     });
   }
   paper.view.draw();
 });
```
