### ISSUE TITLE
Image server

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/digital-fauvel#4]
We will implement a IIIF-compatible image server, to serve all existing facsimiles.

### How to test

1. Go to http://fauvel.archivengine.com/
2. Peruse the facsimiles, of which there should be 96.
3. They should be laid out in a two-up book view, and be zoomable, pannable

**Comment by SteveMarvin** [comment]
There are only 95 leaves. Easiest way to verify is to do a gallery view and count row x items per row. At max view, 19 leaves x 5 rows.

Otherwise everything looks great. Panning and zooming works, two-leaf display is great, and is selectable along the bottom. 👍

**Comment by jamiefolsom** [comment]
Good catch about the number of leaves. That's intentional and expected. It will also change, as Anna selects the exact pages to be used. Thanks!
